<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Engagement - STP</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Mulish:wght@700&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600&display=swap" />
  <link rel="stylesheet" href="../css/engagement.css" />
</head>

<body>
  <div class="main-container">
    <div class="menu">
      <div class="top">
        <div class="logo">
          <div class="logo-stp-oficial">
            <div class="logo-stp-oficial-1">
              <div class="capa"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="bottom">
        <div class="op-menu">
          <div class="menu-2">
            <div class="flex-row-af">
              <div class="rectangle"></div>
              <div class="rectangle-3"></div>
              <div class="rectangle-4"></div>
            </div>
            <div class="flex-row-c">
              <div class="rectangle-5"></div>
              <div class="rectangle-6"></div>
              <div class="rectangle-7"></div>
            </div>
          </div>
        </div>
        <div class="logo-8">
          <div class="logo-k">
            <div class="group">
              <div class="vector"></div>
            </div>
            <div class="group-9">
              <div class="group-a">
                <div class="vector-b"></div>
                <div class="vector-c"></div>
              </div>
              <div class="group-d">
                <div class="vector-e"></div>
                <div class="flex-row-b">
                  <div class="vector-f"></div>
                  <div class="vector-10"></div>
                  <div class="vector-11"></div>
                  <div class="vector-12"></div>
                  <div class="vector-13"></div>
                  <div class="vector-14"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="header">
        <div class="content">
          <span class="api-wasapi">Engagement de KPI’S</span><span class="home-dashboard">Home/ Engagement</span>
        </div>
        <div class="content-15">
          <div class="user">
            <div class="img-perfil"></div>
            <span class="david-castaneda-perez">David Castañeda Perez</span>
          </div>
          <div class="option">
            <div class="vector-16"></div>
          </div>
        </div>
      </div>
      <div class="body">
        <div class="content-17">
          <div class="row">
            <div class="widget">
              <div class="icon">
                <div class="icon-18"></div>
              </div>
              <div class="titulo">
                <span class="consumo-de-contenido">Consumo de Contenido</span>
              </div>
            </div>
            <div class="widget-19">
              <div class="icon-1a">
                <div class="icon-1b"></div>
              </div>
              <div class="titulo-1c">
                <span class="tiempo-de-permanencia">Tiempo de Permanencia</span>
              </div>
            </div>
          </div>
          <div class="row-1d">
            <div class="widget-1e">
              <div class="icon-1f">
                <div class="icon-20"></div>
              </div>
              <div class="titulo-21">
                <span class="consumo-por-canal">Consumo por Canal</span>
              </div>
            </div>
            <div class="widget-22">
              <div class="icon-23">
                <div class="icon-24"></div>
              </div>
              <div class="titulo-25">
                <span class="georeferenciacion">Georeferenciación</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Generated by Codia AI - https://codia.ai/ -->
</body>

</html>